# name
name: Interface Docs

# description
description: Documentation site for the interface repo.

# site theme
theme: jekyll-theme-minimal

# author
author: UND-ARC
author_email: 

show_downloads: true